### ISSUE TITLE
KSM exec command not working on CircleCI

### ISSUE THREAD

**Issue by Hakim187** [Keeper-Security/secrets-manager#243]
i'm trying to create a new command in my keeper orb, which executes the following command : ` ksm exec -- $SHELL`

in order to attribute secrets to my environment vairables in the job, this is how the command is like  : 

`
description: >
  Run a command with secret environment variables loaded from SecretHub

steps:
  - install
  - run:
      name: fetching secrets
      command: ksm exec -- $SHELL
`
  
and this is the job to test it : 

 ```
integration-test-exec-command:
    
    docker:
      - image: cimg/base:stable
    environment:
        MY_USER: keeper://vNrItsdDxL3M9uTuxvzY_g/field/login
    steps:
      - checkout           
      - keeper/exec
```

i'm having this error on circleCI : 

ksm exec -- $SHELL
Imported config saved to profile App1 at keeper.ini.
ksm had a problem: Keeper url missing information about the uid, field type, and field key

it is strange because i have tested the command locally on my machine, and it is working, and i have tried it with all type of executors on CircleCI but it's not working,

Can you please guys take a look on this issue, as we need this command in our workflow, and get back to us
this is quite urgent as we will be fully migrating to keeper by next week  ?
thanks
