### ISSUE TITLE
Missing new line in `ksm init k8s` output with `--immutable` option

### ISSUE THREAD

**Issue by marcozac** [Keeper-Security/secrets-manager#267]
The `ksm init k8s` command output is missing a new line between `type` and `immutable` keys when called with `--immutable` option.

```yaml
...
kind: Secret
metadata:
  name: ksm-config
type: Opaqueimmutable: True
```
It should be easy to resolve with an additional `\n` after `type: Opaque` or before `immutable: True\n`.

https://github.com/Keeper-Security/secrets-manager/blob/5b761f7f3728085d90a66ab3177455de0eea6551/integration/keeper_secrets_manager_cli/keeper_secrets_manager_cli/init.py#L64-L75
